增加 assets 的 i18n 文案; 修改 scene 编辑
VisualSJ/engine-1 pull request #1
Opened 2021-03-03 06:53 UTC by arsen2010

Re: cocos-creator/fireball#

Changelog:
 *

2021-03-03 08:48 UTC, arsen2010 commented
增加只读样式
![image](https://user-images.githubusercontent.com/13517177/109777577-d9461f00-7c3e-11eb-9e93-3e994ab4efc2.png)

2021-03-05 08:59 UTC, VisualSJ approved these changes

2021-03-05 08:59 UTC, VisualSJ commented on editor/i18n/en/localization.js
> +    assets: {
这个独立出去一个文件吧。

2021-03-05 08:59 UTC, VisualSJ commented on editor/i18n/en/localization.js
> -            label: "Basic 3D Features",
这些暂时别动吧，不然回头冲突非常严重。不合理的地方，后续统一再修改

2021-03-05 09:00 UTC, VisualSJ requested changes
尽量少改动 i18n 文件。

2021-03-08 06:59 UTC, arsen2010 commented on editor/i18n/en/localization.js
> +    assets: {
本来是独立出去了，发现 ui-label 里翻译不出来

2021-03-08 08:06 UTC, arsen2010 commented on editor/i18n/en/localization.js
> +    assets: {
已发现原因并处理

2021-03-08 08:06 UTC, arsen2010 commented on editor/i18n/en/localization.js
> -            label: "Basic 3D Features",
已回退格式化

2021-03-09 09:24 UTC, arsen2010 commented
同时解决了 i18n 的问题 https://github.com/cocos-creator/3d-tasks/issues/6447

2021-03-09 09:26 UTC, VisualSJ approved these changes

2021-03-09 09:26 UTC, merged