Add inspector render pipeline
VisualSJ/engine-1 pull request #22
Opened 2021-03-25 02:25 UTC by chichinohaha

里面有我难以解决的逻辑，先合并了请senbing帮忙解决一下

2021-03-25 05:49 UTC, VisualSJ requested changes

2021-03-25 05:49 UTC, VisualSJ commented on editor/inspector/assets.js
> -    texture: join(__dirname, './assets/texture.js'),
为什么删除这两个？

2021-03-25 05:49 UTC, VisualSJ commented on editor/inspector/assets/html.html
> +            <ins-prop auto="true"
ins-prop？

2021-03-25 05:49 UTC, VisualSJ commented on editor/inspector/assets/html.html
> +                @confirm="pipelineIndex = $event.target.value"
```
@confirm？
```

2021-03-26 06:40 UTC, chichinohaha commented
这个分支错了我换一个分支提交

2021-03-26 06:40 UTC, closed without merging